[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr="7654fd0be5bfa9e6eb080229eab8cbb746022fe3ba5cb302fef2d8985d666966"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
