export const NEXT_PUBLIC_CONTRACT_ADDRESS = process.env
  .NEXT_PUBLIC_CONTRACT_ADDRESS as `0x${string}`;
export const NEXT_PUBLIC_BODY_OPTIONS = process.env.NEXT_PUBLIC_BODY_OPTIONS;
export const NEXT_PUBLIC_EAR_OPTIONS = process.env.NEXT_PUBLIC_EAR_OPTIONS;
export const NEXT_PUBLIC_FACE_OPTIONS = process.env.NEXT_PUBLIC_FACE_OPTIONS;
export const NEXT_PUBLIC_ENERGY_INCREASE =
  process.env.NEXT_PUBLIC_ENERGY_INCREASE;
export const NEXT_PUBLIC_ENERGY_DECREASE =
  process.env.NEXT_PUBLIC_ENERGY_DECREASE;
export const NEXT_PUBLIC_ENERGY_CAP = process.env.NEXT_PUBLIC_ENERGY_CAP;

export const MODULE_ADDRESS = "0x7654fd0be5bfa9e6eb080229eab8cbb746022fe3ba5cb302fef2d8985d666966";
